/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABadge: typeof import('ant-design-vue/es')['Badge']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    AInput: typeof import('ant-design-vue/es')['Input']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AResult: typeof import('ant-design-vue/es')['Result']
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    Exception: typeof import('./src/components/System/Exception/index.vue')['default']
    Footer: typeof import('./src/components/System/Footer/index.vue')['default']
    Header: typeof import('./src/components/System/Header/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Logo: typeof import('./src/components/System/Logo/index.vue')['default']
    Main: typeof import('./src/components/System/Layout/Main.vue')['default']
    Menu: typeof import('./src/components/System/Menu/index.vue')['default']
    Mixin: typeof import('./src/components/System/Mixin/index.vue')['default']
    Module: typeof import('./src/components/System/Layout/Module.vue')['default']
    Page: typeof import('./src/components/System/Layout/Page.vue')['default']
    PageContainer: typeof import('./src/components/System/PageContainer/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sider: typeof import('./src/components/System/Sider/index.vue')['default']
    Top: typeof import('./src/components/System/Top/index.vue')['default']
  }
}
